"""rename extra_kwargs col

Revision ID: f3f00df02862
Revises: f0698bc63edd
Create Date: 2023-04-01 18:23:20.668852

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy import JSON, PickleType
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3f00df02862'
down_revision = 'f0698bc63edd'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'extra_kwargs')
    op.add_column('client', sa.Column('extra', JSON, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'extra')
    op.add_column('client', sa.Column('extra_kwargs', PickleType, nullable=True))
    # ### end Alembic commands ###
