"""add delay to actions

Revision ID: c95386a9c812
Revises: f1392b6ac07e
Create Date: 2023-04-20 22:14:05.967671

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

from database.dbmodels.action import ActionType

# revision identifiers, used by Alembic.
revision = 'c95386a9c812'
down_revision = 'f1392b6ac07e'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('delay', sa.Interval(), nullable=True))

    op.execute("ALTER TYPE actiontype RENAME TO actiontype_old")
    actiontype = ENUM(ActionType)
    actiontype.create(op.get_bind())
    op.execute("ALTER TABLE action ALTER COLUMN type TYPE actiontype USING type::text::actiontype")
    op.execute("DROP TYPE actiontype_old")

    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'delay')
    op.execute("ALTER TYPE actiontype RENAME TO actiontype_old")
    actiontype = ENUM('CLIENT', 'TRADE', 'JOURNAL', 'BALANCE', name='actiontype')
    actiontype.create(op.get_bind())
    op.execute("ALTER TABLE action ALTER COLUMN type TYPE actiontype USING type::text::actiontype")
    op.execute("DROP TYPE actiontype_old")

    # ### end Alembic commands ###
