"""add message to action

Revision ID: f1392b6ac07e
Revises: f3f00df02862
Create Date: 2023-04-05 02:59:07.829780

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1392b6ac07e'
down_revision = 'f3f00df02862'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'message')
    # ### end Alembic commands ###
